!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
! MODEL  BFM - Biogeochemical Flux Model
!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
!
! MODULE: set_var_info_bfm
!
! DESCRIPTION
!   This subroutine provides information on the variables. To be used
!   when storing data in NetCDF files.
!   This file is produced by a procedure from a file which include all
!   definitions of global variables and state variables  and a proto-file 
!
! COPYING
!
!   Copyright (C) 2023 BFM System Team (bfm_st@cmcc.it)
!
!   This program is free software: you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation.
!   This program is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTEABILITY or FITNESS FOR A PARTICULAR PURPOSE.
!   See the GNU General Public License for more details.
!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
!
! INCLUDE

subroutine set_var_info_bfm

  use api_bfm
 

!
! 3d variables description:
!
   var_names(1)="O2o"
   var_long(1)="Oxygen"
   var_units(1)="mmol O2/m3"
   var_names(2)="N1p"
   var_long(2)="Phosphate"
   var_units(2)="mmol P/m3"
   var_names(3)="N3n"
   var_long(3)="Nitrate"
   var_units(3)="mmol N/m3"
   var_names(4)="N4n"
   var_long(4)="Ammonium"
   var_units(4)="mmol N/m3"
   var_names(5)="O4n"
   var_long(5)="NitrogenSink"
   var_units(5)="mmol N/m3"
   var_names(6)="N5s"
   var_long(6)="Silicate"
   var_units(6)="mmol Si/m3"
   var_names(7)="N6r"
   var_long(7)="Reduction Equivalents"
   var_units(7)="mmol S--/m3"
   var_names(8)="B1c"
   var_long(8)="Aerobic and Anaerobic Bacteria"
   var_units(8)="mg C/m3"
   var_names(9)="B1n"
   var_long(9)="Aerobic and Anaerobic Bacteria"
   var_units(9)="mmol N/m3"
   var_names(10)="B1p"
   var_long(10)="Aerobic and Anaerobic Bacteria"
   var_units(10)="mmol P/m3"
   var_names(11)="P1c"
   var_long(11)="Diatoms"
   var_units(11)="mg C/m3"
   var_names(12)="P1n"
   var_long(12)="Diatoms"
   var_units(12)="mmol N/m3"
   var_names(13)="P1p"
   var_long(13)="Diatoms"
   var_units(13)="mmol P/m3"
   var_names(14)="P1l"
   var_long(14)="Diatoms"
   var_units(14)="mg Chl/m3"
   var_names(15)="P1s"
   var_long(15)="Diatoms"
   var_units(15)="mmol Si/m3"
   var_names(16)="P2c"
   var_long(16)="Flagellates"
   var_units(16)="mg C/m3"
   var_names(17)="P2n"
   var_long(17)="Flagellates"
   var_units(17)="mmol N/m3"
   var_names(18)="P2p"
   var_long(18)="Flagellates"
   var_units(18)="mmol P/m3"
   var_names(19)="P2l"
   var_long(19)="Flagellates"
   var_units(19)="mg Chl/m3"
   var_names(20)="P3c"
   var_long(20)="PicoPhytoplankton"
   var_units(20)="mg C/m3"
   var_names(21)="P3n"
   var_long(21)="PicoPhytoplankton"
   var_units(21)="mmol N/m3"
   var_names(22)="P3p"
   var_long(22)="PicoPhytoplankton"
   var_units(22)="mmol P/m3"
   var_names(23)="P3l"
   var_long(23)="PicoPhytoplankton"
   var_units(23)="mg Chl/m3"
   var_names(24)="P4c"
   var_long(24)="Large Phytoplankton"
   var_units(24)="mg C/m3"
   var_names(25)="P4n"
   var_long(25)="Large Phytoplankton"
   var_units(25)="mmol N/m3"
   var_names(26)="P4p"
   var_long(26)="Large Phytoplankton"
   var_units(26)="mmol P/m3"
   var_names(27)="P4l"
   var_long(27)="Large Phytoplankton"
   var_units(27)="mg Chl/m3"
   var_names(28)="Z3c"
   var_long(28)="Carnivorous Mesozooplankton"
   var_units(28)="mg C/m3"
   var_names(29)="Z3n"
   var_long(29)="Carnivorous Mesozooplankton"
   var_units(29)="mmol N/m3"
   var_names(30)="Z3p"
   var_long(30)="Carnivorous Mesozooplankton"
   var_units(30)="mmol P/m3"
   var_names(31)="Z4c"
   var_long(31)="Omnivorous Mesozooplankton"
   var_units(31)="mg C/m3"
   var_names(32)="Z4n"
   var_long(32)="Omnivorous Mesozooplankton"
   var_units(32)="mmol N/m3"
   var_names(33)="Z4p"
   var_long(33)="Omnivorous Mesozooplankton"
   var_units(33)="mmol P/m3"
   var_names(34)="Z5c"
   var_long(34)="Microzooplankton"
   var_units(34)="mg C/m3"
   var_names(35)="Z5n"
   var_long(35)="Microzooplankton"
   var_units(35)="mmol N/m3"
   var_names(36)="Z5p"
   var_long(36)="Microzooplankton"
   var_units(36)="mmol P/m3"
   var_names(37)="Z6c"
   var_long(37)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(37)="mg C/m3"
   var_names(38)="Z6n"
   var_long(38)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(38)="mmol N/m3"
   var_names(39)="Z6p"
   var_long(39)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(39)="mmol P/m3"
   var_names(40)="R1c"
   var_long(40)="Labile Dissolved Organic Matter"
   var_units(40)="mg C/m3"
   var_names(41)="R1n"
   var_long(41)="Labile Dissolved Organic Matter"
   var_units(41)="mmol N/m3"
   var_names(42)="R1p"
   var_long(42)="Labile Dissolved Organic Matter"
   var_units(42)="mmol P/m3"
   var_names(43)="R2c"
   var_long(43)="Semi-labile Dissolved Organic Carbon"
   var_units(43)="mg C/m3"
   var_names(44)="R3c"
   var_long(44)="Semi-refractory Dissolved Organic Carbon"
   var_units(44)="mg C/m3"
   var_names(45)="R6c"
   var_long(45)="Particulate Organic Matter"
   var_units(45)="mg C/m3"
   var_names(46)="R6n"
   var_long(46)="Particulate Organic Matter"
   var_units(46)="mmol N/m3"
   var_names(47)="R6p"
   var_long(47)="Particulate Organic Matter"
   var_units(47)="mmol P/m3"
   var_names(48)="R6s"
   var_long(48)="Particulate Organic Matter"
   var_units(48)="mmol Si/m3"
   var_names(49)="O3c"
   var_long(49)="Dissolved Inorganic Carbon"
   var_units(49)="mg C/m3"
   var_names(50)="O3h"
   var_long(50)="Dissolved Inorganic Carbon"
   var_units(50)="mmol eq/m3"
   var_names(51)="O5c"
   var_long(51)="Calcite"
   var_units(51)="mg C/m3"

   var_names(52)="Depth"
   var_long(52)="Gridpoint Depth"
   var_units(52)="m"
   var_names(53)="Volume"
   var_long(53)="Gridpoint Volume"
   var_units(53)="m3"
   var_names(54)="Area"
   var_long(54)="Gridpoint Area"
   var_units(54)="m2"
   var_names(55)="ETW"
   var_long(55)="temperature"
   var_units(55)="C"
   var_names(56)="ESW"
   var_long(56)="Salinity"
   var_units(56)="-"
   var_names(57)="ERHO"
   var_long(57)="Seawater Density"
   var_units(57)="kg/m3"
   var_names(58)="EIR"
   var_long(58)="Irradiance"
   var_units(58)="uE/m2/s"
   var_names(59)="ESS"
   var_long(59)="Suspended Sediments"
   var_units(59)="g/m3"
   var_names(60)="EPR"
   var_long(60)="Water Pressure"
   var_units(60)="dbar"
   var_names(61)="DIC"
   var_long(61)="Dissolved Inorganic Carbon"
   var_units(61)="umol/kg"
   var_names(62)="CO2"
   var_long(62)="CO2(aq)"
   var_units(62)="umol/kg"
   var_names(63)="pCO2"
   var_long(63)="Oceanic pCO2"
   var_units(63)="uatm"
   var_names(64)="HCO3"
   var_long(64)="Bicarbonate"
   var_units(64)="umol/kg"
   var_names(65)="CO3"
   var_long(65)="Carbonate"
   var_units(65)="umol/kg"
   var_names(66)="ALK"
   var_long(66)="Alkalinity"
   var_units(66)="umol eq/kg"
   var_names(67)="pH"
   var_long(67)="pH"
   var_units(67)="-"
   var_names(68)="OCalc"
   var_long(68)="Saturation state of Calcite"
   var_units(68)="-"
   var_names(69)="OArag"
   var_long(69)="Saturation state of Aragonite"
   var_units(69)="-"
   var_names(70)="ffCO2"
   var_long(70)="CO2 fugacity"
   var_units(70)="uatm"
   var_names(71)="totpelc"
   var_long(71)="Total Mass in Pelagic"
   var_units(71)="g C"
   var_names(72)="totpeln"
   var_long(72)="Total Mass in Pelagic"
   var_units(72)="g N"
   var_names(73)="totpelp"
   var_long(73)="Total Mass in Pelagic"
   var_units(73)="g P"
   var_names(74)="totpels"
   var_long(74)="Total Mass in Pelagic"
   var_units(74)="g Si"
   var_names(75)="cxoO2"
   var_long(75)="Oxygen Saturation"
   var_units(75)="mmol O2/m3"
   var_names(76)="eO2mO2"
   var_long(76)="Relative Oxygen saturation"
   var_units(76)="-"
   var_names(77)="Chla"
   var_long(77)="Chlorophyll-a"
   var_units(77)="mg Chl/m3"
   var_names(78)="flPTN6r"
   var_long(78)="Pelagic Anaerobic Mineralization Rate"
   var_units(78)="mmol O2/m3/d"
   var_names(79)="flN3O4n"
   var_long(79)="Pelagic Denitrification Rate"
   var_units(79)="mmol N/m3/d"
   var_names(80)="flN4N3n"
   var_long(80)="Pelagic Nitrification Rate"
   var_units(80)="mmol N/m3/d"
   var_names(81)="sediR2"
   var_long(81)="Colloidal OMT sedimentation rate"
   var_units(81)="m/d"
   var_names(82)="sediR3"
   var_long(82)="Refractory OMT sedimentation rate"
   var_units(82)="m/d"
   var_names(83)="sediR6"
   var_long(83)="Detritus sedimentation rate"
   var_units(83)="m/d"
   var_names(84)="sediO5"
   var_long(84)="Calcite sedimentation rate"
   var_units(84)="m/d"
   var_names(85)="xEPS"
   var_long(85)="Total Extinction Coefficient"
   var_units(85)="1/m"
   var_names(86)="ABIO_eps"
   var_long(86)="Abiotic Extinction Coefficient"
   var_units(86)="1/m"
   var_names(87)="BGE"
   var_long(87)="Bac growth efficiency"
   var_units(87)="-"
   var_names(88)="BIOALK"
   var_long(88)="O3h biological rate of change"
   var_units(88)="mmol/m3"

   var_names(89)="qpcPPY_iiP1"
   var_long(89)="Quotum P/C in Phytoplankton"
   var_units(89)="mmol P/mg C"
   var_names(90)="qpcPPY_iiP2"
   var_long(90)="Quotum P/C in Phytoplankton"
   var_units(90)="mmol P/mg C"
   var_names(91)="qpcPPY_iiP3"
   var_long(91)="Quotum P/C in Phytoplankton"
   var_units(91)="mmol P/mg C"
   var_names(92)="qpcPPY_iiP4"
   var_long(92)="Quotum P/C in Phytoplankton"
   var_units(92)="mmol P/mg C"
   var_names(93)="qncPPY_iiP1"
   var_long(93)="Quotum N/C in Phytoplankton"
   var_units(93)="mmol N/mg C"
   var_names(94)="qncPPY_iiP2"
   var_long(94)="Quotum N/C in Phytoplankton"
   var_units(94)="mmol N/mg C"
   var_names(95)="qncPPY_iiP3"
   var_long(95)="Quotum N/C in Phytoplankton"
   var_units(95)="mmol N/mg C"
   var_names(96)="qncPPY_iiP4"
   var_long(96)="Quotum N/C in Phytoplankton"
   var_units(96)="mmol N/mg C"
   var_names(97)="qscPPY_iiP1"
   var_long(97)="Quotum Si/C in Phytoplankton"
   var_units(97)="mmol Si/mg C"
   var_names(98)="qscPPY_iiP2"
   var_long(98)="Quotum Si/C in Phytoplankton"
   var_units(98)="mmol Si/mg C"
   var_names(99)="qscPPY_iiP3"
   var_long(99)="Quotum Si/C in Phytoplankton"
   var_units(99)="mmol Si/mg C"
   var_names(100)="qscPPY_iiP4"
   var_long(100)="Quotum Si/C in Phytoplankton"
   var_units(100)="mmol Si/mg C"
   var_names(101)="qlcPPY_iiP1"
   var_long(101)="Quotum Chl/C in Phytoplankton"
   var_units(101)="mg Chl /mg C"
   var_names(102)="qlcPPY_iiP2"
   var_long(102)="Quotum Chl/C in Phytoplankton"
   var_units(102)="mg Chl /mg C"
   var_names(103)="qlcPPY_iiP3"
   var_long(103)="Quotum Chl/C in Phytoplankton"
   var_units(103)="mg Chl /mg C"
   var_names(104)="qlcPPY_iiP4"
   var_long(104)="Quotum Chl/C in Phytoplankton"
   var_units(104)="mg Chl /mg C"
   var_names(105)="qccPPY_iiP1"
   var_long(105)="Quotum PIC/POC in Phytoplankton"
   var_units(105)="mg C/mg C"
   var_names(106)="qccPPY_iiP2"
   var_long(106)="Quotum PIC/POC in Phytoplankton"
   var_units(106)="mg C/mg C"
   var_names(107)="qccPPY_iiP3"
   var_long(107)="Quotum PIC/POC in Phytoplankton"
   var_units(107)="mg C/mg C"
   var_names(108)="qccPPY_iiP4"
   var_long(108)="Quotum PIC/POC in Phytoplankton"
   var_units(108)="mg C/mg C"
   var_names(109)="qpcMEZ_iiZ3"
   var_long(109)="Quotum P/C in Mesozooplankton"
   var_units(109)="mmol P/mg C"
   var_names(110)="qpcMEZ_iiZ4"
   var_long(110)="Quotum P/C in Mesozooplankton"
   var_units(110)="mmol P/mg C"
   var_names(111)="qncMEZ_iiZ3"
   var_long(111)="Quotum N/C in Mesozooplankton"
   var_units(111)="mmol N/mg C"
   var_names(112)="qncMEZ_iiZ4"
   var_long(112)="Quotum N/C in Mesozooplankton"
   var_units(112)="mmol N/mg C"
   var_names(113)="qpcMIZ_iiZ5"
   var_long(113)="Quotum P/C in Z5(MicroZooPlankton)"
   var_units(113)="mmol P/mg C"
   var_names(114)="qpcMIZ_iiZ6"
   var_long(114)="Quotum P/C in Z6(MicroZooPlankton)"
   var_units(114)="mmol P/mg C"
   var_names(115)="qncMIZ_iiZ5"
   var_long(115)="Quotum N/C in Z5(MicroZooPlankton)"
   var_units(115)="mmol N/mg C"
   var_names(116)="qncMIZ_iiZ6"
   var_long(116)="Quotum N/C in Z6(MicroZooPlankton)"
   var_units(116)="mmol N/mg C"
   var_names(117)="qpcOMT_iiR1"
   var_long(117)="Quotum P/C in Organic Matter"
   var_units(117)="mmol N/mg C"
   var_names(118)="qpcOMT_iiR2"
   var_long(118)="Quotum P/C in Organic Matter"
   var_units(118)="mmol N/mg C"
   var_names(119)="qpcOMT_iiR3"
   var_long(119)="Quotum P/C in Organic Matter"
   var_units(119)="mmol N/mg C"
   var_names(120)="qpcOMT_iiR6"
   var_long(120)="Quotum P/C in Organic Matter"
   var_units(120)="mmol N/mg C"
   var_names(121)="qncOMT_iiR1"
   var_long(121)="Quotum N/C in Organic Matter"
   var_units(121)="mmol P/mg C"
   var_names(122)="qncOMT_iiR2"
   var_long(122)="Quotum N/C in Organic Matter"
   var_units(122)="mmol P/mg C"
   var_names(123)="qncOMT_iiR3"
   var_long(123)="Quotum N/C in Organic Matter"
   var_units(123)="mmol P/mg C"
   var_names(124)="qncOMT_iiR6"
   var_long(124)="Quotum N/C in Organic Matter"
   var_units(124)="mmol P/mg C"
   var_names(125)="qscOMT_iiR1"
   var_long(125)="Quotum Si/C in Organic Matter"
   var_units(125)="mmol Si/mg C"
   var_names(126)="qscOMT_iiR2"
   var_long(126)="Quotum Si/C in Organic Matter"
   var_units(126)="mmol Si/mg C"
   var_names(127)="qscOMT_iiR3"
   var_long(127)="Quotum Si/C in Organic Matter"
   var_units(127)="mmol Si/mg C"
   var_names(128)="qscOMT_iiR6"
   var_long(128)="Quotum Si/C in Organic Matter"
   var_units(128)="mmol Si/mg C"
   var_names(129)="qpcPBA_iiB1"
   var_long(129)="Quotum P/C in Pelagic Bacteria"
   var_units(129)="mmol P/mg C"
   var_names(130)="qncPBA_iiB1"
   var_long(130)="Quotum N/C in Pelagic Bacteria"
   var_units(130)="mmol N/mg C"
   var_names(131)="sediPPY_iiP1"
   var_long(131)="P1(PhytoPlankton) sedimentation rate"
   var_units(131)="m/d"
   var_names(132)="sediPPY_iiP2"
   var_long(132)="P2(PhytoPlankton) sedimentation rate"
   var_units(132)="m/d"
   var_names(133)="sediPPY_iiP3"
   var_long(133)="P3(PhytoPlankton) sedimentation rate"
   var_units(133)="m/d"
   var_names(134)="sediPPY_iiP4"
   var_long(134)="P4(PhytoPlankton) sedimentation rate"
   var_units(134)="m/d"
   var_names(135)="sediMIZ_iiZ5"
   var_long(135)="Z5(MicroZooPlankton) sedimentation rate"
   var_units(135)="m/d"
   var_names(136)="sediMIZ_iiZ6"
   var_long(136)="Z6(MicroZooPlankton) sedimentation rate"
   var_units(136)="m/d"
   var_names(137)="sediMEZ_iiZ3"
   var_long(137)="Z3(MesoZooPlankton) sedimentation rate"
   var_units(137)="m/d"
   var_names(138)="sediMEZ_iiZ4"
   var_long(138)="Z4(MesoZooPlankton) sedimentation rate"
   var_units(138)="m/d"
   var_names(139)="sunPPY_iiP1"
   var_long(139)="Specific Net Production of P1(PhytoPlankton)"
   var_units(139)="1/d"
   var_names(140)="sunPPY_iiP2"
   var_long(140)="Specific Net Production of P2(PhytoPlankton)"
   var_units(140)="1/d"
   var_names(141)="sunPPY_iiP3"
   var_long(141)="Specific Net Production of P3(PhytoPlankton)"
   var_units(141)="1/d"
   var_names(142)="sunPPY_iiP4"
   var_long(142)="Specific Net Production of P4(PhytoPlankton)"
   var_units(142)="1/d"
   var_names(143)="eiPPY_iiP1"
   var_long(143)="Regulating Factor for Light in P1(PhytoPlankton)"
   var_units(143)="-"
   var_names(144)="eiPPY_iiP2"
   var_long(144)="Regulating Factor for Light in P2(PhytoPlankton)"
   var_units(144)="-"
   var_names(145)="eiPPY_iiP3"
   var_long(145)="Regulating Factor for Light in P3(PhytoPlankton)"
   var_units(145)="-"
   var_names(146)="eiPPY_iiP4"
   var_long(146)="Regulating Factor for Light in P4(PhytoPlankton)"
   var_units(146)="-"
   var_names(147)="ELiPPY_iiP1"
   var_long(147)="Optimal light in P1(PhytoPlankton)"
   var_units(147)="W/m2"
   var_names(148)="ELiPPY_iiP2"
   var_long(148)="Optimal light in P2(PhytoPlankton)"
   var_units(148)="W/m2"
   var_names(149)="ELiPPY_iiP3"
   var_long(149)="Optimal light in P3(PhytoPlankton)"
   var_units(149)="W/m2"
   var_names(150)="ELiPPY_iiP4"
   var_long(150)="Optimal light in P4(PhytoPlankton)"
   var_units(150)="W/m2"

   var_names(151)="ruPPYc"
   var_long(151)="Gross Primary Production"
   var_units(151)="mg C/m3/d"
   var_names(152)="resPPYc"
   var_long(152)="Phytoplankton Respiration"
   var_units(152)="mg C/m3/d"
   var_names(153)="resPBAc"
   var_long(153)="Bacterial Respiration"
   var_units(153)="mg C/m3/d"
   var_names(154)="resZOOc"
   var_long(154)="Zooplankton Respiration"
   var_units(154)="mg C/m3/d"
   var_names(155)="rcalCARc"
   var_long(155)="Calcification rate"
   var_units(155)="mg C/m3/d"
   var_names(156)="ruPPYn"
   var_long(156)="Net Nitrogen Uptake"
   var_units(156)="mmol N/m3/d"
   var_names(157)="ruPPYp"
   var_long(157)="Net Phosphate Uptake"
   var_units(157)="mmol P/m3/d"
   var_names(158)="ruPPYs"
   var_long(158)="Net Silicate Uptake"
   var_units(158)="mmol Si/m3/d"
   var_names(159)="exPPYc"
   var_long(159)="C excretion from phytoplankton"
   var_units(159)="mg C/m3/d"
   var_names(160)="exPPYs"
   var_long(160)="biogenic Si loss from phytoplankton"
   var_units(160)="mmol Si/m3/d"
   var_names(161)="ruZOOc"
   var_long(161)="Gross/Net Secondary Production"
   var_units(161)="mg C/m3/d"
   var_names(162)="resPELo"
   var_long(162)="Pelagic Oxygen Demand"
   var_units(162)="mmol O2/m3/d"
   var_names(163)="remZOOn"
   var_long(163)="Zooplankton N Remineralization"
   var_units(163)="mmol N/m3/d"
   var_names(164)="remZOOp"
   var_long(164)="Zooplankton P Remineralization"
   var_units(164)="mmol P/m3/d"
   var_names(165)="remPBAn"
   var_long(165)="Bacterial N Uptake/Remineralization"
   var_units(165)="mmol N/m3/d"
   var_names(166)="remPBAp"
   var_long(166)="bacterial P Uptake/Remineralization"
   var_units(166)="mmol P/m3/d"
   var_names(167)="remN5s"
   var_long(167)="Si Remineralization"
   var_units(167)="mmol Si/m3/d"


!
!2d Pelagic variables description
   var_names(168)="Area2d"
   var_long(168)="2-D Gridpoint Area"
   var_units(168)="m2"
   var_names(169)="ThereIsLight"
   var_long(169)="Switch for day/night cycle"
   var_units(169)="-"
   var_names(170)="SUNQ"
   var_long(170)="Daylength in hours"
   var_units(170)="h"
   var_names(171)="EWIND"
   var_long(171)="Wind speed"
   var_units(171)="m/s"
   var_names(172)="EICE"
   var_long(172)="Sea-ice fraction"
   var_units(172)="-"
   var_names(173)="ETAUB"
   var_long(173)="Bottom Stress"
   var_units(173)="N m/s"
   var_names(174)="EPCO2air"
   var_long(174)="Atmospheric CO2 Partial Pressure"
   var_units(174)="uatm"
   var_names(175)="CO2airflux"
   var_long(175)="Sea-air CO2 Flux"
   var_units(175)="mmol/m2/d"
   var_names(176)="dpco2"
   var_long(176)="Air-Sea pCO2 difference"
   var_units(176)="uatm"
   var_names(177)="dpo2"
   var_long(177)="Air-Sea pO2 difference"
   var_units(177)="atm"
   var_names(178)="totsysc"
   var_long(178)="total mass"
   var_units(178)="g C"
   var_names(179)="totsysn"
   var_long(179)="total mass"
   var_units(179)="g N"
   var_names(180)="totsysp"
   var_long(180)="total mass"
   var_units(180)="g P"
   var_names(181)="totsyss"
   var_long(181)="total mass"
   var_units(181)="g Si"

!
! surface
!
   var_names(182)="jsurO2o"
   var_long(182)="flux of Oxygen at SURFACE"
   var_units(182)="mmol O2/m2/day"
   var_names(183)="jsurN1p"
   var_long(183)="flux of Phosphate at SURFACE"
   var_units(183)="mmol P/m2/day"
   var_names(184)="jsurN3n"
   var_long(184)="flux of Nitrate at SURFACE"
   var_units(184)="mmol N/m2/day"
   var_names(185)="jsurN4n"
   var_long(185)="flux of Ammonium at SURFACE"
   var_units(185)="mmol N/m2/day"
   var_names(186)="jsurO4n"
   var_long(186)="flux of NitrogenSink at SURFACE"
   var_units(186)="mmol N/m2/day"
   var_names(187)="jsurN5s"
   var_long(187)="flux of Silicate at SURFACE"
   var_units(187)="mmol Si/m2/day"
   var_names(188)="jsurN6r"
   var_long(188)="flux of Reduction Equivalents at SURFACE"
   var_units(188)="mmol S--/m2/day"
   var_names(189)="jsurB1c"
   var_long(189)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(189)="mg C/m2/day"
   var_names(190)="jsurB1n"
   var_long(190)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(190)="mmol N/m2/day"
   var_names(191)="jsurB1p"
   var_long(191)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(191)="mmol P/m2/day"
   var_names(192)="jsurP1c"
   var_long(192)="flux of Diatoms at SURFACE"
   var_units(192)="mg C/m2/day"
   var_names(193)="jsurP1n"
   var_long(193)="flux of Diatoms at SURFACE"
   var_units(193)="mmol N/m2/day"
   var_names(194)="jsurP1p"
   var_long(194)="flux of Diatoms at SURFACE"
   var_units(194)="mmol P/m2/day"
   var_names(195)="jsurP1l"
   var_long(195)="flux of Diatoms at SURFACE"
   var_units(195)="mg Chl/m2/day"
   var_names(196)="jsurP1s"
   var_long(196)="flux of Diatoms at SURFACE"
   var_units(196)="mmol Si/m2/day"
   var_names(197)="jsurP2c"
   var_long(197)="flux of Flagellates at SURFACE"
   var_units(197)="mg C/m2/day"
   var_names(198)="jsurP2n"
   var_long(198)="flux of Flagellates at SURFACE"
   var_units(198)="mmol N/m2/day"
   var_names(199)="jsurP2p"
   var_long(199)="flux of Flagellates at SURFACE"
   var_units(199)="mmol P/m2/day"
   var_names(200)="jsurP2l"
   var_long(200)="flux of Flagellates at SURFACE"
   var_units(200)="mg Chl/m2/day"
   var_names(201)="jsurP3c"
   var_long(201)="flux of PicoPhytoplankton at SURFACE"
   var_units(201)="mg C/m2/day"
   var_names(202)="jsurP3n"
   var_long(202)="flux of PicoPhytoplankton at SURFACE"
   var_units(202)="mmol N/m2/day"
   var_names(203)="jsurP3p"
   var_long(203)="flux of PicoPhytoplankton at SURFACE"
   var_units(203)="mmol P/m2/day"
   var_names(204)="jsurP3l"
   var_long(204)="flux of PicoPhytoplankton at SURFACE"
   var_units(204)="mg Chl/m2/day"
   var_names(205)="jsurP4c"
   var_long(205)="flux of Large Phytoplankton at SURFACE"
   var_units(205)="mg C/m2/day"
   var_names(206)="jsurP4n"
   var_long(206)="flux of Large Phytoplankton at SURFACE"
   var_units(206)="mmol N/m2/day"
   var_names(207)="jsurP4p"
   var_long(207)="flux of Large Phytoplankton at SURFACE"
   var_units(207)="mmol P/m2/day"
   var_names(208)="jsurP4l"
   var_long(208)="flux of Large Phytoplankton at SURFACE"
   var_units(208)="mg Chl/m2/day"
   var_names(209)="jsurZ3c"
   var_long(209)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(209)="mg C/m2/day"
   var_names(210)="jsurZ3n"
   var_long(210)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(210)="mmol N/m2/day"
   var_names(211)="jsurZ3p"
   var_long(211)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(211)="mmol P/m2/day"
   var_names(212)="jsurZ4c"
   var_long(212)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(212)="mg C/m2/day"
   var_names(213)="jsurZ4n"
   var_long(213)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(213)="mmol N/m2/day"
   var_names(214)="jsurZ4p"
   var_long(214)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(214)="mmol P/m2/day"
   var_names(215)="jsurZ5c"
   var_long(215)="flux of Microzooplankton at SURFACE"
   var_units(215)="mg C/m2/day"
   var_names(216)="jsurZ5n"
   var_long(216)="flux of Microzooplankton at SURFACE"
   var_units(216)="mmol N/m2/day"
   var_names(217)="jsurZ5p"
   var_long(217)="flux of Microzooplankton at SURFACE"
   var_units(217)="mmol P/m2/day"
   var_names(218)="jsurZ6c"
   var_long(218)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(218)="mg C/m2/day"
   var_names(219)="jsurZ6n"
   var_long(219)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(219)="mmol N/m2/day"
   var_names(220)="jsurZ6p"
   var_long(220)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(220)="mmol P/m2/day"
   var_names(221)="jsurR1c"
   var_long(221)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(221)="mg C/m2/day"
   var_names(222)="jsurR1n"
   var_long(222)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(222)="mmol N/m2/day"
   var_names(223)="jsurR1p"
   var_long(223)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(223)="mmol P/m2/day"
   var_names(224)="jsurR2c"
   var_long(224)="flux of Semi-labile Dissolved Organic Carbon at SURFACE"
   var_units(224)="mg C/m2/day"
   var_names(225)="jsurR3c"
   var_long(225)="flux of Semi-refractory Dissolved Organic Carbon at SURFACE"
   var_units(225)="mg C/m2/day"
   var_names(226)="jsurR6c"
   var_long(226)="flux of Particulate Organic Matter at SURFACE"
   var_units(226)="mg C/m2/day"
   var_names(227)="jsurR6n"
   var_long(227)="flux of Particulate Organic Matter at SURFACE"
   var_units(227)="mmol N/m2/day"
   var_names(228)="jsurR6p"
   var_long(228)="flux of Particulate Organic Matter at SURFACE"
   var_units(228)="mmol P/m2/day"
   var_names(229)="jsurR6s"
   var_long(229)="flux of Particulate Organic Matter at SURFACE"
   var_units(229)="mmol Si/m2/day"
   var_names(230)="jsurO3c"
   var_long(230)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(230)="mg C/m2/day"
   var_names(231)="jsurO3h"
   var_long(231)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(231)="mmol eq/m2/day"
   var_names(232)="jsurO5c"
   var_long(232)="flux of Calcite at SURFACE"
   var_units(232)="mg C/m2/day"

!
! bottom
!
   var_names(233)="jbotO2o"
   var_long(233)="flux of Oxygen at BOTTOM"
   var_units(233)="mmol O2/m2/day"
   var_names(234)="jbotN1p"
   var_long(234)="flux of Phosphate at BOTTOM"
   var_units(234)="mmol P/m2/day"
   var_names(235)="jbotN3n"
   var_long(235)="flux of Nitrate at BOTTOM"
   var_units(235)="mmol N/m2/day"
   var_names(236)="jbotN4n"
   var_long(236)="flux of Ammonium at BOTTOM"
   var_units(236)="mmol N/m2/day"
   var_names(237)="jbotO4n"
   var_long(237)="flux of NitrogenSink at BOTTOM"
   var_units(237)="mmol N/m2/day"
   var_names(238)="jbotN5s"
   var_long(238)="flux of Silicate at BOTTOM"
   var_units(238)="mmol Si/m2/day"
   var_names(239)="jbotN6r"
   var_long(239)="flux of Reduction Equivalents at BOTTOM"
   var_units(239)="mmol S--/m2/day"
   var_names(240)="jbotB1c"
   var_long(240)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(240)="mg C/m2/day"
   var_names(241)="jbotB1n"
   var_long(241)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(241)="mmol N/m2/day"
   var_names(242)="jbotB1p"
   var_long(242)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(242)="mmol P/m2/day"
   var_names(243)="jbotP1c"
   var_long(243)="flux of Diatoms at BOTTOM"
   var_units(243)="mg C/m2/day"
   var_names(244)="jbotP1n"
   var_long(244)="flux of Diatoms at BOTTOM"
   var_units(244)="mmol N/m2/day"
   var_names(245)="jbotP1p"
   var_long(245)="flux of Diatoms at BOTTOM"
   var_units(245)="mmol P/m2/day"
   var_names(246)="jbotP1l"
   var_long(246)="flux of Diatoms at BOTTOM"
   var_units(246)="mg Chl/m2/day"
   var_names(247)="jbotP1s"
   var_long(247)="flux of Diatoms at BOTTOM"
   var_units(247)="mmol Si/m2/day"
   var_names(248)="jbotP2c"
   var_long(248)="flux of Flagellates at BOTTOM"
   var_units(248)="mg C/m2/day"
   var_names(249)="jbotP2n"
   var_long(249)="flux of Flagellates at BOTTOM"
   var_units(249)="mmol N/m2/day"
   var_names(250)="jbotP2p"
   var_long(250)="flux of Flagellates at BOTTOM"
   var_units(250)="mmol P/m2/day"
   var_names(251)="jbotP2l"
   var_long(251)="flux of Flagellates at BOTTOM"
   var_units(251)="mg Chl/m2/day"
   var_names(252)="jbotP3c"
   var_long(252)="flux of PicoPhytoplankton at BOTTOM"
   var_units(252)="mg C/m2/day"
   var_names(253)="jbotP3n"
   var_long(253)="flux of PicoPhytoplankton at BOTTOM"
   var_units(253)="mmol N/m2/day"
   var_names(254)="jbotP3p"
   var_long(254)="flux of PicoPhytoplankton at BOTTOM"
   var_units(254)="mmol P/m2/day"
   var_names(255)="jbotP3l"
   var_long(255)="flux of PicoPhytoplankton at BOTTOM"
   var_units(255)="mg Chl/m2/day"
   var_names(256)="jbotP4c"
   var_long(256)="flux of Large Phytoplankton at BOTTOM"
   var_units(256)="mg C/m2/day"
   var_names(257)="jbotP4n"
   var_long(257)="flux of Large Phytoplankton at BOTTOM"
   var_units(257)="mmol N/m2/day"
   var_names(258)="jbotP4p"
   var_long(258)="flux of Large Phytoplankton at BOTTOM"
   var_units(258)="mmol P/m2/day"
   var_names(259)="jbotP4l"
   var_long(259)="flux of Large Phytoplankton at BOTTOM"
   var_units(259)="mg Chl/m2/day"
   var_names(260)="jbotZ3c"
   var_long(260)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(260)="mg C/m2/day"
   var_names(261)="jbotZ3n"
   var_long(261)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(261)="mmol N/m2/day"
   var_names(262)="jbotZ3p"
   var_long(262)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(262)="mmol P/m2/day"
   var_names(263)="jbotZ4c"
   var_long(263)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(263)="mg C/m2/day"
   var_names(264)="jbotZ4n"
   var_long(264)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(264)="mmol N/m2/day"
   var_names(265)="jbotZ4p"
   var_long(265)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(265)="mmol P/m2/day"
   var_names(266)="jbotZ5c"
   var_long(266)="flux of Microzooplankton at BOTTOM"
   var_units(266)="mg C/m2/day"
   var_names(267)="jbotZ5n"
   var_long(267)="flux of Microzooplankton at BOTTOM"
   var_units(267)="mmol N/m2/day"
   var_names(268)="jbotZ5p"
   var_long(268)="flux of Microzooplankton at BOTTOM"
   var_units(268)="mmol P/m2/day"
   var_names(269)="jbotZ6c"
   var_long(269)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(269)="mg C/m2/day"
   var_names(270)="jbotZ6n"
   var_long(270)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(270)="mmol N/m2/day"
   var_names(271)="jbotZ6p"
   var_long(271)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(271)="mmol P/m2/day"
   var_names(272)="jbotR1c"
   var_long(272)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(272)="mg C/m2/day"
   var_names(273)="jbotR1n"
   var_long(273)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(273)="mmol N/m2/day"
   var_names(274)="jbotR1p"
   var_long(274)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(274)="mmol P/m2/day"
   var_names(275)="jbotR2c"
   var_long(275)="flux of Semi-labile Dissolved Organic Carbon at BOTTOM"
   var_units(275)="mg C/m2/day"
   var_names(276)="jbotR3c"
   var_long(276)="flux of Semi-refractory Dissolved Organic Carbon at BOTTOM"
   var_units(276)="mg C/m2/day"
   var_names(277)="jbotR6c"
   var_long(277)="flux of Particulate Organic Matter at BOTTOM"
   var_units(277)="mg C/m2/day"
   var_names(278)="jbotR6n"
   var_long(278)="flux of Particulate Organic Matter at BOTTOM"
   var_units(278)="mmol N/m2/day"
   var_names(279)="jbotR6p"
   var_long(279)="flux of Particulate Organic Matter at BOTTOM"
   var_units(279)="mmol P/m2/day"
   var_names(280)="jbotR6s"
   var_long(280)="flux of Particulate Organic Matter at BOTTOM"
   var_units(280)="mmol Si/m2/day"
   var_names(281)="jbotO3c"
   var_long(281)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(281)="mg C/m2/day"
   var_names(282)="jbotO3h"
   var_long(282)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(282)="mmol eq/m2/day"
   var_names(283)="jbotO5c"
   var_long(283)="flux of Calcite at BOTTOM"
   var_units(283)="mg C/m2/day"


#ifdef INCLUDE_SEAICE
!
!2d SeaIce variables description




#endif

!
!2d Benthic variables description
   var_names(284)="Q1c"
   var_long(284)="Surface Sediment Labile organic Matter"
   var_units(284)="mg C/m2"
   var_names(285)="Q1n"
   var_long(285)="Surface Sediment Labile organic Matter"
   var_units(285)="mmol N/m2"
   var_names(286)="Q1p"
   var_long(286)="Surface Sediment Labile organic Matter"
   var_units(286)="mmol P/m2"
   var_names(287)="Q11c"
   var_long(287)="Deep Sediment Labile organic Matter"
   var_units(287)="mg C/m2"
   var_names(288)="Q11n"
   var_long(288)="Deep Sediment Labile organic Matter"
   var_units(288)="mmol N/m2"
   var_names(289)="Q11p"
   var_long(289)="Deep Sediment Labile organic Matter"
   var_units(289)="mmol P/m2"
   var_names(290)="Q6c"
   var_long(290)="Surface Sediment Particulate organic Matter"
   var_units(290)="mg C/m2"
   var_names(291)="Q6n"
   var_long(291)="Surface Sediment Particulate organic Matter"
   var_units(291)="mmol N/m2"
   var_names(292)="Q6p"
   var_long(292)="Surface Sediment Particulate organic Matter"
   var_units(292)="mmol P/m2"
   var_names(293)="Q6s"
   var_long(293)="Surface Sediment Particulate organic Matter"
   var_units(293)="mmol Si/m2"
   var_names(294)="Q16c"
   var_long(294)="Deep Sediment Particulate organic Matter"
   var_units(294)="mg C/m2"
   var_names(295)="Q16n"
   var_long(295)="Deep Sediment Particulate organic Matter"
   var_units(295)="mmol N/m2"
   var_names(296)="Q16p"
   var_long(296)="Deep Sediment Particulate organic Matter"
   var_units(296)="mmol P/m2"
   var_names(297)="Q16s"
   var_long(297)="Deep Sediment Particulate organic Matter"
   var_units(297)="mmol Si/m2"

   var_names(298)="totbenc"
   var_long(298)="total mass present in benthos"
   var_units(298)="g C"
   var_names(299)="totbenn"
   var_long(299)="total mass present in benthos"
   var_units(299)="g N"
   var_names(300)="totbenp"
   var_long(300)="total mass present in benthos"
   var_units(300)="g P"
   var_names(301)="totbens"
   var_long(301)="total mass present in benthos"
   var_units(301)="g Si"

   var_names(302)="qpcBOM_iiQ1"
   var_long(302)="Quotum P/C in Benthic Organic Matter"
   var_units(302)="mmol N/mg C"
   var_names(303)="qpcBOM_iiQ11"
   var_long(303)="Quotum P/C in Benthic Organic Matter"
   var_units(303)="mmol N/mg C"
   var_names(304)="qpcBOM_iiQ6"
   var_long(304)="Quotum P/C in Benthic Organic Matter"
   var_units(304)="mmol N/mg C"
   var_names(305)="qpcBOM_iiQ16"
   var_long(305)="Quotum P/C in Benthic Organic Matter"
   var_units(305)="mmol N/mg C"
   var_names(306)="qncBOM_iiQ1"
   var_long(306)="Quotum N/C in Benthic Organic Matter"
   var_units(306)="mmol P/mg C"
   var_names(307)="qncBOM_iiQ11"
   var_long(307)="Quotum N/C in Benthic Organic Matter"
   var_units(307)="mmol P/mg C"
   var_names(308)="qncBOM_iiQ6"
   var_long(308)="Quotum N/C in Benthic Organic Matter"
   var_units(308)="mmol P/mg C"
   var_names(309)="qncBOM_iiQ16"
   var_long(309)="Quotum N/C in Benthic Organic Matter"
   var_units(309)="mmol P/mg C"
   var_names(310)="qscBOM_iiQ1"
   var_long(310)="Quotum Si/C in Benthic Organic Matter"
   var_units(310)="mmol Si/mg C"
   var_names(311)="qscBOM_iiQ11"
   var_long(311)="Quotum Si/C in Benthic Organic Matter"
   var_units(311)="mmol Si/mg C"
   var_names(312)="qscBOM_iiQ6"
   var_long(312)="Quotum Si/C in Benthic Organic Matter"
   var_units(312)="mmol Si/mg C"
   var_names(313)="qscBOM_iiQ16"
   var_long(313)="Quotum Si/C in Benthic Organic Matter"
   var_units(313)="mmol Si/mg C"

   var_names(314)="burC"
   var_long(314)="Burial of POC in deep sediments"
   var_units(314)="mgC/m2/d"



!
!Index Pelagic
!
   stPelStart=1
   stPelEnd=283


   stPelStateS=1
   stPelStateE=51

   stPelDiagS=52
   stPelDiagE=150

   stPelFluxS=151
   stPelFluxE=167

   stPelDiag2dS=168
   stPelDiag2dE=181

   stPelSurS=182
   stPelSurE=232

   stPelBotS=233
   stPelBotE=283



#ifdef INCLUDE_SEAICE
!
!Index SeaIce
!
   stIceStart=284
   stIceEnd=283


   stIceStateS=284
   stIceStateE=283

   stIceDiag2dS=284
   stIceDiag2dE=283

   stIceFlux2dS=284
   stIceFlux2dE=283


#endif

!
!Index Benthic
!
   stBenStart=284
   stBenEnd=314


   stBenStateS=284
   stBenStateE=297

   stBenDiag2dS=298
   stBenDiag2dE=313

   stBenFlux2dS=314
   stBenFlux2dE=314



   stStart=1
   stEnd=314


end subroutine set_var_info_bfm

!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
! MODEL  BFM - Biogeochemical Flux Model
!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
